# Types
documentation:
    - '/type documentation'

bug:
    - '/type bug'

enhancement:
    - '/type feature'

ci:
    - '/label ci'

cli:
    - '/label cli'

task:
    - '/type task'

# Labels
json-configuration:
    - '/label json-configuration'

github-action:
    - '/label github-action'

github-provider:
    - '/label github-provider'

test-automation:
    - '/label test-automation'